name = "JuliaVlasov"
uuid = "a6fc13a9-8b56-4a3f-85ad-d3f47fb09b2c"
repo = "https://github.com/JuliaVlasov/Registry.git"
description = "Registry for Julia Vlasov packages"

[packages]
abe12ce6-d865-11e8-314f-3f926d5bd47d = { name = "SemiLagrangian", path = "S/SemiLagrangian" }
